import type { User, Conversation, Notification, MarketplaceItem, SwapRequest } from "@/lib/types";
import placeholderData from "@/lib/placeholder-images.json";
import { ALL_SKILLS } from "@/lib/skills";

const { placeholderImages } = placeholderData;

const imageMap = new Map(placeholderImages.map(image => [image.id, image]));

const findImage = (id: string) => {
    const image = imageMap.get(id);
    return {
        imageUrl: image?.imageUrl ?? `https://placehold.co/200x200?text=${id}`,
        imageHint: image?.imageHint ?? "placeholder"
    };
};

export const users: User[] = [
  {
    id: "user-1",
    name: "Adanna Chioma",
    email: "adanna@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Passionate graphic designer with a love for typography and branding. Looking to learn pottery to unwind and create with my hands.",
    location: "Lagos, LA",
    skillsOffered: ["Graphic Design", "Illustration", "Branding"],
    skillsNeeded: ["Pottery", "Creative Writing"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-2",
    name: "Bolanle Adebayo",
    email: "bolanle@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Software developer by day, aspiring chef by night. I can build you a website in exchange for some authentic Nigerian cooking lessons.",
    location: "Abuja, FCT",
    skillsOffered: ["Web Development", "React", "Node.js"],
    skillsNeeded: ["Cooking", "Guitar"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active 2 days ago",
    status: 'offline',
  },
  {
    id: "user-3",
    name: "Chinedu Okafor",
    email: "chinedu@example.com",
    avatarUrl: findImage("user-3").imageUrl,
    avatarHint: findImage("user-3").imageHint,
    bio: "I'm a writer and editor looking to get my finances in order. I can help you with your blog or manuscript!",
    location: "Kano, KN",
    skillsOffered: ["Creative Writing", "Editing", "Content Strategy"],
    skillsNeeded: ["Personal Finance", "Graphic Design"],
    isVerified: false,
    rating: 4.5,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-4",
    name: "Dayo Olumide",
    email: "dayo@example.com",
    avatarUrl: findImage("user-4").imageUrl,
    avatarHint: findImage("user-4").imageHint,
    bio: "Fitness instructor and nutritionist. I can create a personalized workout and meal plan for you. Seeking help with social media marketing.",
    location: "Ibadan, OY",
    skillsOffered: ["Fitness Coaching", "Nutrition Planning"],
    skillsNeeded: ["Social Media Marketing", "Web Development"],
    isVerified: true,
    rating: 5.0,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-5",
    name: "Emeka Nwosu",
    email: "emeka@example.com",
    avatarUrl: findImage("user-5").imageUrl,
    avatarHint: findImage("user-5").imageHint,
    bio: "Skilled carpenter and woodworker. Can build custom furniture. I'd love to learn how to play the guitar.",
    location: "Port Harcourt, RV",
    skillsOffered: ["Carpentry", "Woodworking"],
    skillsNeeded: ["Guitar"],
    isVerified: true,
    rating: 4.7,
    lastActive: "Active yesterday",
    status: 'offline',
  },
   {
    id: "user-6",
    name: "Fatima Bello",
    email: "fatima@example.com",
    avatarUrl: findImage("user-6").imageUrl,
    avatarHint: findImage("user-6").imageHint,
    bio: "Expert in public speaking and presentation skills. Looking to learn basic coding to build a personal project.",
    location: "Kaduna, KD",
    skillsOffered: ["Public Speaking", "Presentation Design"],
    skillsNeeded: ["React", "Node.js"],
    isVerified: false,
    rating: 4.6,
    lastActive: "Active 4 hours ago",
    status: 'online',
  },
  {
    id: "user-7",
    name: "Gbenga Adekunle",
    email: "george@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Architect looking to trade building design tips for learning about urban gardening.",
    location: "Lagos, LA",
    skillsOffered: ["Architecture"],
    skillsNeeded: ["Urban Gardening"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-8",
    name: "Habiba Ibrahim",
    email: "habiba@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Pop star by night, normal teen by day. Can teach singing in exchange for advanced math tutoring.",
    location: "Benin City, ED",
    skillsOffered: ["Singing"],
    skillsNeeded: ["Calculus"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active 5 days ago",
    status: 'offline',
  },
  {
    id: "user-9",
    name: "Ifeanyi Okoro",
    email: "ifeanyi@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "I've got a few laws of physics to share. I'm interested in learning about modern-day alchemy, or 'chemistry' as you call it.",
    location: "Enugu, EN",
    skillsOffered: ["Physics"],
    skillsNeeded: ["Chemistry"],
    isVerified: false,
    rating: 4.2,
    lastActive: "Active 2 weeks ago",
    status: 'offline',
  },
  {
    id: "user-10",
    name: "Jide Sanusi",
    email: "jide@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "I'm a photographer who wants to learn how to bake sourdough bread. I can take professional portraits for you!",
    location: "Jos, PL",
    skillsOffered: ["Photography"],
    skillsNeeded: ["Baking"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active yesterday",
    status: 'offline',
  },
  {
    id: "user-11",
    name: "Kemi Alabi",
    email: "kemi@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Expert in home defense systems. Looking for someone to teach me how to speak French.",
    location: "Abeokuta, OG",
    skillsOffered: ["Home Security"],
    skillsNeeded: ["French"],
    isVerified: false,
    rating: 4.4,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-12",
    name: "Lola Palmer",
    email: "laura@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Homecoming queen. I can teach you about... secrets. Looking to learn knitting.",
    location: "Calabar, CR",
    skillsOffered: ["Event Planning"],
    skillsNeeded: ["Knitting"],
    isVerified: true,
    rating: 4.7,
    lastActive: "Active 1 hour ago",
    status: 'online',
  },
  {
    id: "user-13",
    name: "Musa Adeboye",
    email: "musa@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "World's Best Boss. Can teach management and improv comedy. Need help with my video editing for 'Threat Level Midnight'.",
    location: "Ilorin, KW",
    skillsOffered: ["Sales", "Improv"],
    skillsNeeded: ["Video Editing"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-14",
    name: "Ngozi Eze",
    email: "ngozi@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Amateur detective. I can find anything! I'd like to learn car maintenance for my blue roadster.",
    location: "Owerri, IM",
    skillsOffered: ["Problem Solving"],
    skillsNeeded: ["Car Maintenance"],
    isVerified: false,
    rating: 4.1,
    lastActive: "Active 3 days ago",
    status: 'offline',
  },
  {
    id: "user-15",
    name: "Obioma Nwankwo",
    email: "obioma@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "I can teach you the importance of being earnest. In return, I'd like to learn about this 'internet' thing.",
    location: "Uyo, AK",
    skillsOffered: ["Playwriting"],
    skillsNeeded: ["Web Development"],
    isVerified: true,
    rating: 4.6,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-16",
    name: "Patience Ozokwor",
    email: "patience@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Artist and former receptionist. I can teach watercolor painting. I'm looking for lessons in public speaking.",
    location: "Asaba, DT",
    skillsOffered: ["Watercolor Painting"],
    skillsNeeded: ["Public Speaking"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-17",
    name: "Quadri Abbas",
    email: "quadri@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "I make films. I can teach you about dialogue and non-linear storytelling. I need someone to teach me how to use a smartphone properly.",
    location: "Lokoja, KG",
    skillsOffered: ["Filmmaking"],
    skillsNeeded: ["Smartphone Basics"],
    isVerified: false,
    rating: 4.3,
    lastActive: "Active last month",
    status: 'offline',
  },
  {
    id: "user-18",
    name: "Remi Tinubu",
    email: "remi@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Fashion enthusiast. I can give you a complete style makeover. I want to learn how to cook something other than a trifle with beef.",
    location: "Lagos, LA",
    skillsOffered: ["Fashion Styling"],
    skillsNeeded: ["Cooking"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active yesterday",
    status: 'offline',
  },
  {
    id: "user-19",
    name: "Segun Arinze",
    email: "segun@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "I can do this all day. Can teach strategic leadership and super soldier combat. I need to learn about modern art.",
    location: "Abuja, FCT",
    skillsOffered: ["Leadership"],
    skillsNeeded: ["Art History"],
    isVerified: true,
    rating: 5.0,
    lastActive: "Active 2 hours ago",
    status: 'online',
  },
  {
    id: "user-20",
    name: "Tunde Ednut",
    email: "tunde@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Genius, billionaire, playboy, philanthropist. Can teach robotics and AI. Looking to learn how to relax and do yoga.",
    location: "Port Harcourt, RV",
    skillsOffered: ["Robotics"],
    skillsNeeded: ["Yoga"],
    isVerified: false,
    rating: 4.0,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-21",
    name: "Uche Jombo",
    email: "uche@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "I write stories about other worlds. Can teach world-building and narrative structure. I want to learn about astronomy.",
    location: "Kano, KN",
    skillsOffered: ["Creative Writing"],
    skillsNeeded: ["Astronomy"],
    isVerified: true,
    rating: 4.7,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-22",
    name: "Victor Osimhen",
    email: "victor@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "A man of science. Can teach anatomy and reanimation. I'm looking for lessons in ethics and moral philosophy.",
    location: "Ibadan, OY",
    skillsOffered: ["Anatomy"],
    skillsNeeded: ["Ethics"],
    isVerified: true,
    rating: 4.5,
    lastActive: "Active 6 days ago",
    status: 'offline',
  },
  {
    id: "user-23",
    name: "Wale Adenuga",
    email: "wale@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Chemistry teacher. I can teach you a lot about chemistry. I need help with my car wash business.",
    location: "Kaduna, KD",
    skillsOffered: ["Chemistry"],
    skillsNeeded: ["Business Management"],
    isVerified: false,
    rating: 4.2,
    lastActive: "Active 2 weeks ago",
    status: 'offline',
  },
  {
    id: "user-24",
    name: "Xavier Thorpe",
    email: "xavier@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Warrior Princess. Can teach you how to use a chakram and fight for the greater good. I'd like to learn pottery.",
    location: "Benin City, ED",
    skillsOffered: ["Self-Defense"],
    skillsNeeded: ["Pottery"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active yesterday",
    status: 'offline',
  },
  {
    id: "user-25",
    name: "Yemi Alade",
    email: "yemi@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Teach you, I can. Learn, you will. How to build a modern web app, I wish to learn.",
    location: "Enugu, EN",
    skillsOffered: ["Meditation"],
    skillsNeeded: ["React"],
    isVerified: true,
    rating: 5.0,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-26",
    name: "Zainab Balogun",
    email: "zainab@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Princess of Hyrule. I can teach royal etiquette and Ocarina songs. I need help fixing my Sheikah Slate.",
    location: "Jos, PL",
    skillsOffered: ["Music"],
    skillsNeeded: ["Electronics Repair"],
    isVerified: false,
    rating: 4.3,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-27",
    name: "Abubakar Dumbledore",
    email: "albus@hogwarts.edu",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "wise wizard",
    bio: "Headmaster. Can offer lessons in transfiguration and defense against the dark arts. Seeking to understand 'the internet'.",
    location: "Abeokuta, OG",
    skillsOffered: ["Transfiguration", "Ancient Runes" ],
    skillsNeeded: ["Web Development"],
    isVerified: true,
    rating: 5.0,
    lastActive: "Active 1 month ago",
    status: 'offline',
  },
  {
    id: "user-28",
    name: "Bisola Omoge",
    email: "beatrix@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "female warrior",
    bio: "Can teach sword fighting and the five-point-palm exploding heart technique. I'm interested in learning how to knit.",
    location: "Calabar, CR",
    skillsOffered: ["Swordsmanship"],
    skillsNeeded: ["Knitting"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-29",
    name: "Chukwudi Kramer",
    email: "kramer@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "quirky man",
    bio: "I'm full of ideas! I can teach you about physical comedy and making a grand entrance. I need someone to help me with my taxes.",
    location: "Ilorin, KW",
    skillsOffered: ["Improv"],
    skillsNeeded: ["Personal Finance"],
    isVerified: false,
    rating: 4.0,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-30",
    name: "Damola Scully",
    email: "scully@fbi.gov",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "female detective",
    bio: "Medical doctor and FBI agent. I can teach you about forensic science and skepticism. I'm looking to learn photography.",
    location: "Owerri, IM",
    skillsOffered: ["Forensic Science"],
    skillsNeeded: ["Photography"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active yesterday",
    status: 'offline',
  },
  {
    id: "user-31",
    name: "Ezinne Benes",
    email: "elaine@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "woman city",
    bio: "I work in publishing. I can edit your manuscript and teach you how to dance... sort of. I want to learn how to do my own plumbing.",
    location: "Uyo, AK",
    skillsOffered: ["Editing"],
    skillsNeeded: ["Plumbing"],
    isVerified: false,
    rating: 4.2,
    lastActive: "Active 2 days ago",
    status: 'offline',
  },
  {
    id: "user-32",
    name: "Folarin Mulder",
    email: "mulder@fbi.gov",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "male detective",
    bio: "I want to believe. Can teach you about unsolved mysteries and the paranormal. Looking for someone to teach me advanced basketball techniques.",
    location: "Asaba, DT",
    skillsOffered: ["Creative Writing"],
    skillsNeeded: ["Basketball"],
    isVerified: true,
    rating: 4.6,
    lastActive: "Active 10 hours ago",
    status: 'online',
  },
  {
    id: "user-33",
    name: "Gideon Ramsay",
    email: "gordon@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "chef angry",
    bio: "I can teach you how to cook like a real chef. Don't be an idiot sandwich. I'd like to learn how to be more patient.",
    location: "Lokoja, KG",
    skillsOffered: ["Cooking"],
    skillsNeeded: ["Meditation"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active now",
    status: 'online',
  },
  {
    id: "user-34",
    name: "Halima Granger",
    email: "hermione@hogwarts.edu",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "student wizard",
    bio: "I can help you with pretty much any subject. I'm particularly good at Arithmancy. I want to learn how to use a computer.",
    location: "Lagos, LA",
    skillsOffered: ["Research"],
    skillsNeeded: ["Computer Basics"],
    isVerified: false,
    rating: 4.7,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-35",
    name: "Idris Jones",
    email: "indy@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "adventurer fedora",
    bio: "Archaeology professor and adventurer. I can teach you about ancient history and how to use a whip. I need to learn how to fly a plane.",
    location: "Abuja, FCT",
    skillsOffered: ["Archaeology"],
    skillsNeeded: ["Piloting"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active 3 days ago",
    status: 'offline',
  },
  {
    id: "user-36",
    name: "Jelani Sparrow",
    email: "captainjack@sea.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "pirate captain",
    bio: "Captain. I can teach you how to sail and find treasure. Savvy? I need someone to fix my compass.",
    location: "Port Harcourt, RV",
    skillsOffered: ["Sailing"],
    skillsNeeded: ["Electronics Repair"],
    isVerified: true,
    rating: 4.5,
    lastActive: "Active yesterday",
    status: 'offline',
  },
  {
    id: "user-37",
    name: "Kuburat Everdeen",
    email: "katniss@district12.panem",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "archer woods",
    bio: "I can teach you archery and survival skills. I'd like to learn how to bake.",
    location: "Kano, KN",
    skillsOffered: ["Archery"],
    skillsNeeded: ["Baking"],
    isVerified: false,
    rating: 4.9,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-38",
    name: "Linda Lemon",
    email: "liz@nbc.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "woman office",
    bio: "Head writer for a sketch comedy show. I can teach you how to write jokes. I need help with my night cheese addiction.",
    location: "Ibadan, OY",
    skillsOffered: ["Comedy Writing"],
    skillsNeeded: ["Nutrition Planning"],
    isVerified: true,
    rating: 4.4,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-39",
    name: "Mohammed McFly",
    email: "marty@hillvalley.ca",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "teenager 80s",
    bio: "I can play the guitar pretty well. I need someone to help me fix my DeLorean.",
    location: "Kaduna, KD",
    skillsOffered: ["Guitar"],
    skillsNeeded: ["Car Maintenance"],
    isVerified: false,
    rating: 4.6,
    lastActive: "Active 2 hours ago",
    status: 'online',
  },
  {
    id: "user-40",
    name: "Olu Prime",
    email: "optimus@autobots.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "robot leader",
    bio: "Leader of the Autobots. I can teach you about leadership and intergalactic diplomacy. I wish to learn about human art.",
    location: "Benin City, ED",
    skillsOffered: ["Leadership"],
    skillsNeeded: ["Art History"],
    isVerified: true,
    rating: 5.0,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-41",
    name: "Peter Obi",
    email: "pete@dailybugle.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "young man",
    bio: "I'm a freelance photographer. I can teach you how to take great pictures. I'm trying to learn more about chemistry.",
    location: "Enugu, EN",
    skillsOffered: ["Photography"],
    skillsNeeded: ["Chemistry"],
    isVerified: true,
    rating: 4.7,
    lastActive: "Active 4 days ago",
    status: 'offline',
  },
  {
    id: "user-42",
    name: "Rotimi Swanson",
    email: "ron@pawnee.in.gov",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "man mustache",
    bio: "I enjoy woodworking and breakfast food. I can teach you how to build a canoe. I have no needs.",
    location: "Jos, PL",
    skillsOffered: ["Woodworking"],
    skillsNeeded: ["Philosophy"],
    isVerified: false,
    rating: 4.8,
    lastActive: "Active last week",
    status: 'offline',
  },
  {
    id: "user-43",
    name: "Simi Connor",
    email: "sarah@resistance.net",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "woman tough",
    bio: "I can teach you how to survive judgment day. I need to learn how to weld.",
    location: "Abeokuta, OG",
    skillsOffered: ["Survival Skills"],
    skillsNeeded: ["Welding"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-44",
    name: "Sheriff Holmes",
    email: "sherlock@221b.baker.st",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "detective classic",
    bio: "Consulting detective. I can teach you the science of deduction. I'm looking for someone to teach me the violin.",
    location: "Calabar, CR",
    skillsOffered: ["Problem Solving"],
    skillsNeeded: ["Violin"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active yesterday",
    status: 'offline',
  },
  {
    id: "user-45",
    name: "Wale Wonka",
    email: "wonka@factory.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "eccentric man",
    bio: "Chocolatier. I can teach you how to make candy. I need help with my factory's accounting.",
    location: "Ilorin, KW",
    skillsOffered: ["Baking"],
    skillsNeeded: ["Personal Finance"],
    isVerified: false,
    rating: 4.5,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-46",
    name: "Anselm Skywalker",
    email: "ani@jedicouncil.org",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "young jedi",
    bio: "Jedi Knight. Expert pilot and lightsaber duelist. I can teach you pod-racing. Looking to learn sand-castle building.",
    location: "Owerri, IM",
    skillsOffered: ["Piloting", "Swordsmanship"],
    skillsNeeded: ["Sculpting"],
    isVerified: true,
    rating: 4.7,
    lastActive: "Active 5 hours ago",
    status: 'online',
  },
  {
    id: "user-47",
    name: "Bimbo Baggins",
    email: "bilbo@bagend.shire",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "hobbit home",
    bio: "I've been on an adventure. I can teach you map-making and riddles. Seeking lessons in dragon-slaying, just in case.",
    location: "Uyo, AK",
    skillsOffered: ["Storytelling"],
    skillsNeeded: ["Swordsmanship"],
    isVerified: false,
    rating: 4.6,
    lastActive: "Active 3 weeks ago",
    status: 'offline',
  },
  {
    id: "user-48",
    name: "Chioma Sandiego",
    email: "carmen@vile.org",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "woman red",
    bio: "International art thief. I can teach you geography and history. Looking for someone to teach me how to code.",
    location: "Asaba, DT",
    skillsOffered: ["Geography"],
    skillsNeeded: ["Web Development"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-49",
    name: "Doctor Dele",
    email: "the.doctor@tardis.time",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "time traveler",
    bio: "Time Lord. I can teach you about all of time and space. I need help fixing my chameleon circuit.",
    location: "Lokoja, KG",
    skillsOffered: ["History"],
    skillsNeeded: ["Electronics Repair"],
    isVerified: true,
    rating: 5.0,
    lastActive: "Active now",
    status: 'online',
  },
  {
    id: "user-50",
    name: "Femi Gump",
    email: "forrest@bubbagump.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "man simple",
    bio: "I'm not a smart man, but I know what love is. I can teach you how to run, play ping-pong, and shrimp. I want to learn about computers.",
    location: "Lagos, LA",
    skillsOffered: ["Running"],
    skillsNeeded: ["Web Development"],
    isVerified: false,
    rating: 4.9,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-51",
    name: "Gollum",
    email: "myprecious@middle-earth.net",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "creature dark",
    bio: "We knows riddles, yes we do. We can teach you how to catch fish with our hands. We needs our precious.",
    location: "Abuja, FCT",
    skillsOffered: ["Riddles"],
    skillsNeeded: ["Jewelry Making"],
    isVerified: true,
    rating: 3.5,
    lastActive: "Active last year",
    status: 'offline',
  },
  {
    id: "user-52",
    name: "James Bond",
    email: "007@mi6.gov.uk",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "spy tuxedo",
    bio: "Shaken, not stirred. I can teach you espionage and card games. I'm looking for someone to teach me how to make a proper martini at home.",
    location: "Port Harcourt, RV",
    skillsOffered: ["Problem Solving"],
    skillsNeeded: ["Mixology"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active yesterday",
    status: 'offline',
  },
  {
    id: "user-53",
    name: "Lekan",
    email: "legolas@mirkwood.elf",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "elf archer",
    bio: "Elf of the woodland realm. My eyes are keen. I can teach you archery and how to walk on snow. I wish to learn the ways of the Dwarves.",
    location: "Kano, KN",
    skillsOffered: ["Archery"],
    skillsNeeded: ["Stonemasonry"],
    isVerified: false,
    rating: 4.7,
    lastActive: "Active 2 days ago",
    status: 'offline',
  },
  {
    id: "user-54",
    name: "Mary Poppins",
    email: "mary@cherrytreelane.uk",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "nanny vintage",
    bio: "Practically perfect in every way. I can teach you how to have a tidy nursery and how to fly a kite. I'm looking to learn how to skateboard.",
    location: "Ibadan, OY",
    skillsOffered: ["Child Care"],
    skillsNeeded: ["Skateboarding"],
    isVerified: true,
    rating: 5.0,
    lastActive: "Active now",
    status: 'online',
  },
  {
    id: "user-55",
    name: "Nnamdi",
    email: "thomas.anderson@metacortex.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "man trenchcoat",
    bio: "I know kung fu. I can teach you how to free your mind. I need someone to explain what 'tastee wheat' is.",
    location: "Kaduna, KD",
    skillsOffered: ["Kung Fu"],
    skillsNeeded: ["Cooking"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active 1 hour ago",
    status: 'online',
  },
  {
    id: "user-56",
    name: "Richard Balboa",
    email: "rocky@philly.net",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "boxer determined",
    bio: "It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward. I can teach you boxing. I want to learn how to read better.",
    location: "Benin City, ED",
    skillsOffered: ["Boxing"],
    skillsNeeded: ["Literacy"],
    isVerified: false,
    rating: 4.9,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-57",
    name: "Ada Lovelace",
    email: "ada@example.com",
    avatarUrl: "https://picsum.photos/seed/user57/200/200",
    avatarHint: "woman historical",
    bio: "I'm an analyst and metaphysician. I can teach you about analytical engines. I'm looking to learn about poetry.",
    location: "Lagos, LA",
    skillsOffered: ["Analysis", "Mathematics"],
    skillsNeeded: ["Poetry"],
    isVerified: true,
    rating: 4.7,
    lastActive: "Active last month",
    status: 'offline',
  },
  {
    id: "user-58",
    name: "Burna Boy",
    email: "burna@example.com",
    avatarUrl: "https://picsum.photos/seed/user58/200/200",
    avatarHint: "musician african",
    bio: "African Giant. I can teach you how to create afrobeats. I'm looking to learn how to cook jollof rice.",
    location: "Port Harcourt, RV",
    skillsOffered: ["Music Production", "Songwriting"],
    skillsNeeded: ["Cooking"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-59",
    name: "Chimamanda Adichie",
    email: "chimamanda@example.com",
    avatarUrl: "https://picsum.photos/seed/user59/200/200",
    avatarHint: "author nigerian",
    bio: "I'm a writer. I can teach you about storytelling. I'm looking to learn how to use social media.",
    location: "Enugu, EN",
    skillsOffered: ["Creative Writing", "Storytelling"],
    skillsNeeded: ["Social Media Marketing"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active yesterday",
    status: 'offline',
  },
  {
    id: "user-60",
    name: "Davido Adeleke",
    email: "davido@example.com",
    avatarUrl: "https://picsum.photos/seed/user60/200/200",
    avatarHint: "musician afrobeat",
    bio: "OBO. I can teach you how to make hit songs. I'm looking to learn how to invest in real estate.",
    location: "Atlanta, GA",
    skillsOffered: ["Songwriting", "Music Production"],
    skillsNeeded: ["Investing"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active now",
    status: 'online',
  },
  {
    id: "user-61",
    name: "Ebenezer Obey",
    email: "ebenezer@example.com",
    avatarUrl: "https://picsum.photos/seed/user61/200/200",
    avatarHint: "musician juju",
    bio: "I'm a juju musician. I can teach you how to play the guitar. I'm looking to learn how to use a computer.",
    location: "Abeokuta, OG",
    skillsOffered: ["Guitar", "Music"],
    skillsNeeded: ["Computer Basics"],
    isVerified: false,
    rating: 4.5,
    lastActive: "Active this month",
    status: 'offline',
  },
  {
    id: "user-62",
    name: "Funke Akindele",
    email: "funke@example.com",
    avatarUrl: "https://picsum.photos/seed/user62/200/200",
    avatarHint: "actress producer",
    bio: "I'm an actress and producer. I can teach you about acting and film production. I'm looking to learn how to code.",
    location: "Lagos, LA",
    skillsOffered: ["Acting", "Filmmaking"],
    skillsNeeded: ["Web Development"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active 2 days ago",
    status: 'offline',
  },
  {
    id: "user-63",
    name: "Genevieve Nnaji",
    email: "genevieve@example.com",
    avatarUrl: "https://picsum.photos/seed/user63/200/200",
    avatarHint: "actress director",
    bio: "I'm an actress and director. I can teach you about the film industry. I'm looking to learn how to paint.",
    location: "Lagos, LA",
    skillsOffered: ["Acting", "Filmmaking"],
    skillsNeeded: ["Painting"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-64",
    name: "Herbert Macaulay",
    email: "herbert@example.com",
    avatarUrl: "https://picsum.photos/seed/user64/200/200",
    avatarHint: "nationalist historical",
    bio: "I'm a nationalist. I can teach you about Nigerian history. I'm looking to learn about modern politics.",
    location: "Lagos, LA",
    skillsOffered: ["History"],
    skillsNeeded: ["Political Science"],
    isVerified: false,
    rating: 4.2,
    lastActive: "Active last year",
    status: 'offline',
  },
  {
    id: "user-65",
    name: "Innocent Idibia",
    email: "2face@example.com",
    avatarUrl: "https://picsum.photos/seed/user65/200/200",
    avatarHint: "musician nigerian",
    bio: "I'm a musician. I can teach you how to write a song. I'm looking to learn how to play the piano.",
    location: "Jos, PL",
    skillsOffered: ["Songwriting", "Music"],
    skillsNeeded: ["Piano"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active 10 days ago",
    status: 'offline',
  },
  {
    id: "user-66",
    name: "J.P. Clark",
    email: "jp@example.com",
    avatarUrl: "https://picsum.photos/seed/user66/200/200",
    avatarHint: "poet playwright",
    bio: "I'm a poet and playwright. I can teach you about literature. I'm looking to learn how to use a computer.",
    location: "Lagos, LA",
    skillsOffered: ["Poetry", "Playwriting"],
    skillsNeeded: ["Computer Basics"],
    isVerified: false,
    rating: 4.4,
    lastActive: "Active last month",
    status: 'offline',
  },
  {
    id: "user-67",
    name: "King Sunny Adé",
    email: "ksa@example.com",
    avatarUrl: "https://picsum.photos/seed/user67/200/200",
    avatarHint: "musician guitar",
    bio: "I'm a juju musician. I can teach you how to play the guitar. I'm looking to learn about music production.",
    location: "Ondo, OD",
    skillsOffered: ["Guitar", "Music"],
    skillsNeeded: ["Music Production"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-68",
    name: "Lagbaja",
    email: "lagbaja@example.com",
    avatarUrl: "https://picsum.photos/seed/user68/200/200",
    avatarHint: "musician masked",
    bio: "I'm a musician. I can teach you how to play the saxophone. I'm looking to learn how to remain anonymous.",
    location: "Lagos, LA",
    skillsOffered: ["Saxophone", "Music"],
    skillsNeeded: ["Cryptography"],
    isVerified: true,
    rating: 4.7,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-69",
    name: "Miriam Makeba",
    email: "miriam@example.com",
    avatarUrl: "https://picsum.photos/seed/user69/200/200",
    avatarHint: "singer activist",
    bio: "Mama Africa. I can teach you how to sing. I'm looking to learn about social media activism.",
    location: "Johannesburg, SA",
    skillsOffered: ["Singing"],
    skillsNeeded: ["Social Media Marketing"],
    isVerified: false,
    rating: 4.8,
    lastActive: "Active last week",
    status: 'offline',
  },
  {
    id: "user-70",
    name: "Nnamdi Azikiwe",
    email: "z.ik@example.com",
    avatarUrl: "https://picsum.photos/seed/user70/200/200",
    avatarHint: "president historical",
    bio: "I'm a statesman. I can teach you about political science. I'm looking to learn about computer programming.",
    location: "Onitsha, AN",
    skillsOffered: ["Political Science"],
    skillsNeeded: ["Python"],
    isVerified: false,
    rating: 4.3,
    lastActive: "Active 2 months ago",
    status: 'offline',
  },
  {
    id: "user-71",
    name: "Olamide Adedeji",
    email: "olamide@example.com",
    avatarUrl: "https://picsum.photos/seed/user71/200/200",
    avatarHint: "rapper producer",
    bio: "Baddo. I can teach you how to rap and produce music. I'm looking to learn about fashion.",
    location: "Lagos, LA",
    skillsOffered: ["Music Production", "Rap"],
    skillsNeeded: ["Fashion Design"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active 3 hours ago",
    status: 'online',
  },
  {
    id: "user-72",
    name: "Pete Edochie",
    email: "pete@example.com",
    avatarUrl: "https://picsum.photos/seed/user72/200/200",
    avatarHint: "actor veteran",
    bio: "I'm a veteran actor. I can teach you about acting. I'm looking to learn how to use a smartphone.",
    location: "Enugu, EN",
    skillsOffered: ["Acting"],
    skillsNeeded: ["Smartphone Basics"],
    isVerified: false,
    rating: 4.7,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-73",
    name: "Queen Amina",
    email: "amina@example.com",
    avatarUrl: "https://picsum.photos/seed/user73/200/200",
    avatarHint: "warrior queen",
    bio: "I'm a warrior queen. I can teach you about military strategy. I'm looking to learn how to build fortifications.",
    location: "Zaria, KD",
    skillsOffered: ["Leadership", "Strategy"],
    skillsNeeded: ["Architecture"],
    isVerified: false,
    rating: 4.9,
    lastActive: "Active centuries ago",
    status: 'offline',
  },
  {
    id: "user-74",
    name: "Ramsey Nouah",
    email: "ramsey@example.com",
    avatarUrl: "https://picsum.photos/seed/user74/200/200",
    avatarHint: "actor director",
    bio: "I'm an actor and director. I can teach you about filmmaking. I'm looking to learn how to write a script.",
    location: "Lagos, LA",
    skillsOffered: ["Acting", "Filmmaking"],
    skillsNeeded: ["Creative Writing"],
    isVerified: true,
    rating: 4.8,
    lastActive: "Active yesterday",
    status: 'offline',
  },
  {
    id: "user-75",
    name: "Sade Adu",
    email: "sade@example.com",
    avatarUrl: "https://picsum.photos/seed/user75/200/200",
    avatarHint: "singer songwriter",
    bio: "I'm a singer and songwriter. I can teach you how to write a song. I'm looking to learn how to garden.",
    location: "London, UK",
    skillsOffered: ["Songwriting", "Singing"],
    skillsNeeded: ["Urban Gardening"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active this month",
    status: 'offline',
  },
  {
    id: "user-76",
    name: "Tiwa Savage",
    email: "tiwa@example.com",
    avatarUrl: "https://picsum.photos/seed/user76/200/200",
    avatarHint: "singer afrobeat",
    bio: "Number one African bad gyal. I can teach you how to perform on stage. I'm looking to learn about business management.",
    location: "Lagos, LA",
    skillsOffered: ["Singing", "Performance"],
    skillsNeeded: ["Business Management"],
    isVerified: true,
    rating: 4.9,
    lastActive: "Active today",
    status: 'online',
  },
  {
    id: "user-77",
    name: "Usman dan Fodio",
    email: "usman@example.com",
    avatarUrl: "https://picsum.photos/seed/user77/200/200",
    avatarHint: "scholar historical",
    bio: "I'm a scholar. I can teach you about Islamic studies. I'm looking to learn about modern technology.",
    location: "Sokoto, SO",
    skillsOffered: ["Theology", "History"],
    skillsNeeded: ["Computer Basics"],
    isVerified: false,
    rating: 4.5,
    lastActive: "Active centuries ago",
    status: 'offline',
  },
  {
    id: "user-78",
    name: "Wizkid",
    email: "wizkid@example.com",
    avatarUrl: "https://picsum.photos/seed/user78/200/200",
    avatarHint: "musician starboy",
    bio: "Starboy. I can teach you how to make music that travels the world. I'm looking to learn how to paint.",
    location: "Lagos, LA",
    skillsOffered: ["Music Production", "Songwriting"],
    skillsNeeded: ["Painting"],
    isVerified: true,
    rating: 5.0,
    lastActive: "Active now",
    status: 'online',
  },
  {
    id: "user-79",
    name: "Wole Soyinka",
    email: "wole@example.com",
    avatarUrl: "https://picsum.photos/seed/user79/200/200",
    avatarHint: "author nobel",
    bio: "I'm a writer. I can teach you about literature and human rights. I'm looking to learn how to use a computer.",
    location: "Abeokuta, OG",
    skillsOffered: ["Creative Writing", "Playwriting"],
    skillsNeeded: ["Computer Basics"],
    isVerified: true,
    rating: 5.0,
    lastActive: "Active this week",
    status: 'offline',
  },
  {
    id: "user-80",
    name: "Yusuf Grillo",
    email: "yusuf@example.com",
    avatarUrl: "https://picsum.photos/seed/user80/200/200",
    avatarHint: "artist painter",
    bio: "I'm an artist. I can teach you how to paint. I'm looking to learn about digital art.",
    location: "Lagos, LA",
    skillsOffered: ["Painting"],
    skillsNeeded: ["Adobe Photoshop"],
    isVerified: false,
    rating: 4.8,
    lastActive: "Active last month",
    status: 'offline',
  },
];


export const conversations: Conversation[] = [
  {
    id: "conv-1",
    participant: users.find(u => u.id === 'user-2')!,
    messages: [
       { id: "msg-1-1", senderId: "user-2", text: "Hey Adanna! I saw on your profile you're looking to learn pottery. I'm just starting out but I've got a wheel at home if you'd ever want to practice together.", timestamp: "2024-05-20T10:00:00Z" },
       { id: "msg-1-2", senderId: "user-1", text: "That sounds amazing, Bolanle! I'd love that. I've been wanting to try for ages but didn't know where to start.", timestamp: "2024-05-20T10:05:00Z" },
       { id: "msg-1-3", senderId: "user-1", text: "By the way, I saw you're a developer. I could definitely help you with some logo ideas for a portfolio or a cooking blog if you're interested. It's what I do!", timestamp: "2024-05-20T10:06:00Z" },
       { id: "msg-1-4", senderId: "user-2", text: "Wow, that's a perfect swap! I was just thinking about starting a food blog. Your design work is incredible.", timestamp: "2024-05-20T10:10:00Z" },
       { id: "msg-1-5", senderId: "user-2", text: "How about this weekend? I'm free on Saturday afternoon. We can get our hands dirty with some clay.", timestamp: "2024-05-20T10:11:00Z" },
       { id: "msg-1-6", senderId: "user-1", text: "Saturday works for me! I'm so excited. I'll bring some sketches for your blog logo. ✨", timestamp: "2024-05-20T10:15:00Z" },
    ],
    get lastMessage() { return this.messages[this.messages.length - 1] },
  },
    {
    id: "conv-2",
    participant: users.find(u => u.id === 'user-3')!,
    messages: [
      { id: "msg-2-1", senderId: "user-3", text: "Hi Adanna, your design portfolio is stunning. I'm a writer and I'm looking for some help with a cover for my manuscript. Would you be open to a swap?", timestamp: "2024-05-19T14:30:00Z" },
      { id: "msg-2-2", senderId: "user-1", text: "Hi Chinedu! Thank you so much. I'd be happy to take a look. Funnily enough, I'm trying to get back into creative writing myself. Maybe we can help each other out?", timestamp: "2024-05-19T14:35:00Z" },
      { id: "msg-2-3", senderId: "user-3", text: "That's a fantastic idea. I could give you some writing prompts or edit a short story for you in exchange for some cover concepts.", timestamp: "2024-05-19T14:40:00Z" },
      { id: "msg-2-4", senderId: "user-1", text: "[Image attached: initial-concept-1.jpg] Here's a very rough first idea I had based on your book's synopsis. No pressure at all, just a thought starter!", timestamp: "2024-05-21T11:00:00Z" },
      { id: "msg-2-5", senderId: "user-3", text: "Wow, I love the direction! You're fast. Let's schedule a call to talk about it more. And I'll send you those writing exercises now.", timestamp: "2024-05-21T11:05:00Z" },
    ],
    get lastMessage() { return this.messages[this.messages.length - 1] },
  },
  {
    id: "conv-3",
    participant: users.find(u => u.id === 'user-4')!,
    messages: [
      { id: "msg-3-1", senderId: "user-4", text: "Proposal: I'll trade you a 1-month fitness and nutrition plan for some help setting up a social media strategy for my coaching business. Interested?", timestamp: "2024-05-22T09:00:00Z" },
      { id: "msg-3-2", senderId: "user-1", text: "Hi Dayo, yes! Absolutely. I've been wanting to get back on track with my fitness. Your profile looks great.", timestamp: "2024-05-22T09:05:00Z" },
      { id: "msg-3-3", senderId: "user-4", text: "Awesome. Let's start with a quick call to discuss your goals. I can also give you access to my client portal. I need help figuring out Instagram and TikTok.", timestamp: "2024-05-22T09:10:00Z" },
      { id: "msg-3-4", senderId: "user-1", text: "Perfect. I can definitely help with that. I'll draft a content calendar and some post ideas for you this week.", timestamp: "2024-05-22T09:12:00Z" },
    ],
    get lastMessage() { return this.messages[this.messages.length - 1] },
  },
  {
    id: "conv-4",
    participant: users.find(u => u.id === 'user-5')!,
    messages: [
      { id: "msg-4-1", senderId: "user-1", text: "Hi Emeka, I saw you offer carpentry lessons. I've always wanted to build my own bookshelf. Your work is beautiful!", timestamp: "2024-05-21T18:00:00Z" },
      { id: "msg-4-2", senderId: "user-5", text: "Thanks, Adanna. A bookshelf is a great first project. I can teach you the basics. I see you're a designer... could you help me design a logo for my woodworking business?", timestamp: "2024-05-21T18:05:00Z" },
      { id: "msg-4-3", senderId: "user-1", text: "That's a deal! How about we meet at your workshop next week? I'll bring my laptop.", timestamp: "2024-05-21T18:10:00Z" },
      { id: "msg-4-4", senderId: "user-5", text: "[Video sent: workshop_tour.mp4] Sounds like a plan. Here's a quick tour of the space. Let me know what day works for you.", timestamp: "2024-05-21T18:15:00Z" },
      { id: "msg-4-5", senderId: "user-1", text: "The workshop looks amazing! How about Tuesday evening?", timestamp: "2024-05-21T18:20:00Z" },
      { id: "msg-4-6", senderId: "user-5", text: "Tuesday is perfect. See you then.", timestamp: "2024-05-21T18:21:00Z" },
      { id: "msg-4-7", senderId: "user-1", text: "Great! Looking forward to it.", timestamp: "2024-05-21T18:22:00Z" },
      { id: "msg-4-8", senderId: "user-5", text: "Don't forget to wear closed-toe shoes.", timestamp: "2024-05-21T18:23:00Z" },
    ],
    get lastMessage() { return this.messages[this.messages.length - 1] },
  },
];

export const notifications: Notification[] = [
    {
        id: "notif-1",
        type: 'message',
        title: "New Message from Bolanle Adebayo",
        description: "Saturday works for me! I'm so excited...",
        timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
        read: false,
        user: {
            name: "Bolanle Adebayo",
            avatarUrl: findImage("user-2").imageUrl,
            avatarHint: findImage("user-2").imageHint,
        }
    },
    {
        id: "notif-2",
        type: 'swap',
        title: "Swap Accepted!",
        description: "Dayo Olumide accepted your proposal to swap Fitness Coaching for Social Media Marketing.",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        read: false,
        user: {
            name: "Dayo Olumide",
            avatarUrl: findImage("user-4").imageUrl,
            avatarHint: findImage("user-4").imageHint,
        }
    },
    {
        id: "notif-3",
        type: 'ai',
        title: "New AI Matches Found",
        description: "We found 3 new users who need skills you offer. Check them out!",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        read: false,
    },
    {
        id: "notif-4",
        type: 'message',
        title: "New Message from Chinedu Okafor",
        description: "Wow, I love the direction! You're fast...",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
        read: true,
        user: {
            name: "Chinedu Okafor",
            avatarUrl: findImage("user-3").imageUrl,
            avatarHint: findImage("user-3").imageHint,
        }
    },
];

export const marketplaceItems: MarketplaceItem[] = [
    {
        id: 'item-1',
        title: 'The Ultimate Guide to Sourdough',
        author: 'Jide Sanusi',
        price: 7500,
        imageUrl: findImage('ebook-1').imageUrl,
        imageHint: findImage('ebook-1').imageHint,
        type: 'eBook',
        isSoldOut: false,
        preview: "Chapter 1: The Starter. It all begins with flour and water. The starter, or levain, is a living culture of wild yeasts and bacteria that will give your bread its characteristic tangy flavor and airy crumb. In this chapter, we'll cover how to create your starter from scratch, what to feed it, and how to know when it's ready to use. It's a journey of patience, but the reward is worth it."
    },
    {
        id: 'item-2',
        title: 'Canva Social Media Templates',
        author: 'Adanna Chioma',
        price: 12000,
        imageUrl: findImage('template-1').imageUrl,
        imageHint: findImage('template-1').imageHint,
        type: 'Template',
        isSoldOut: false,
        preview: "This pack includes 25 professionally designed Canva templates for Instagram posts and stories. The templates are fully customizable, allowing you to change colors, fonts, and images to match your brand. A watermarked preview image shows a grid of beautifully designed, modern social media layouts with placeholder text and images. They feature clean lines and a consistent color palette."
    },
    {
        id: 'item-3',
        title: 'React Component Library',
        author: 'Bolanle Adebayo',
        price: 35000,
        imageUrl: findImage('tool-1').imageUrl,
        imageHint: findImage('tool-1').imageHint,
        type: 'Tool',
        isSoldOut: true,
        preview: "This is a premium component library and cannot be previewed."
    },
    {
        id: 'item-4',
        title: 'Beginner\'s Guide to Fitness',
        author: 'Dayo Olumide',
        price: 4500,
        imageUrl: findImage('guide-1').imageUrl,
        imageHint: findImage('guide-1').imageHint,
        type: 'Guide',
        isSoldOut: false,
        preview: "Introduction: Your Fitness Journey. Welcome! This guide is designed for absolute beginners who want to take the first step towards a healthier lifestyle. We'll cover the basics of cardiovascular exercise, strength training, and nutrition. You don't need a fancy gym membership to get started. All you need is a little bit of space and a lot of motivation. Let's begin."
    },
     {
        id: 'item-5',
        title: 'Woodworking Project Plans',
        author: 'Emeka Nwosu',
        price: 5500,
        imageUrl: findImage('ebook-2').imageUrl,
        imageHint: findImage('ebook-2').imageHint,
        type: 'Guide',
        isSoldOut: false,
        preview: "Project 1: The Simple Bookshelf. This guide provides step-by-step instructions for building a classic three-shelf bookshelf. You will need: three 1x12 pine boards, a saw, a drill, and wood screws. The preview includes a watermarked blueprint showing the dimensions and assembly instructions. It's the perfect project for a beginner to get comfortable with basic woodworking techniques."
    },
    {
        id: 'item-6',
        title: 'Public Speaking Confidence Kit',
        author: 'Fatima Bello',
        price: 14000,
        imageUrl: findImage('guide-2').imageUrl,
        imageHint: findImage('guide-2').imageHint,
        type: 'Guide',
        isSoldOut: false,
        preview: "Module 1: Overcoming Stage Fright. The fear of public speaking is incredibly common. In this first section, we will explore breathing techniques and mental exercises to calm your nerves before you even step on stage. One simple technique is the 4-7-8 breathing method: inhale for 4 seconds, hold for 7, and exhale for 8. Try it now."
    },
    {
        id: 'item-7',
        title: 'Advanced SEO Strategies 2024',
        author: 'Segun Arinze',
        price: 90000,
        imageUrl: 'https://picsum.photos/seed/mp7/600/400',
        imageHint: 'data analytics',
        type: 'eBook',
        isSoldOut: false,
        preview: "Chapter 1: Beyond Keywords. While keywords are still important, modern SEO is about semantic search and user intent. This chapter delves into understanding topic clusters and creating content that answers questions, not just matches search terms. We'll analyze how Google's BERT and MUM updates have changed the game and what you need to do to stay ahead."
    },
    {
        id: 'item-8',
        title: 'Notion Planner for Creatives',
        author: 'Uche Jombo',
        price: 10000,
        imageUrl: 'https://picsum.photos/seed/mp8/600/400',
        imageHint: 'organized desk',
        type: 'Template',
        isSoldOut: false,
        preview: "A watermarked screenshot of a Notion dashboard is shown. It includes sections for 'Project Timelines', 'Idea Sandbox', 'Content Calendar', and 'Inspiration Board'. The layout is clean and minimalist, using icons and columns to organize information effectively. This template is designed to be your all-in-one workspace for creative projects."
    },
    {
        id: 'item-9',
        title: 'Introduction to Python Course',
        author: 'Victor Osimhen',
        price: 20000,
        imageUrl: 'https://picsum.photos/seed/mp9/600/400',
        imageHint: 'python code',
        type: 'Guide',
        isSoldOut: true,
        preview: "Lesson 1: Hello, World! In the world of programming, the first step is always to make the computer say 'Hello, World!'. This simple exercise confirms that your environment is set up correctly. In Python, this is incredibly simple. Just type: print('Hello, World!'). This preview shows the first three lessons, covering variables, data types, and basic operators."
    },
    {
        id: 'item-10',
        title: 'Figma UI Kit for Startups',
        author: 'Adanna Chioma',
        price: 25000,
        imageUrl: 'https://picsum.photos/seed/mp10/600/400',
        imageHint: 'UI design',
        type: 'Tool',
        isSoldOut: false,
        preview: "This UI Kit for Figma includes over 100+ components to help you design your next project faster. The preview shows a watermarked image of various components like buttons, input fields, cards, and navigation bars in different states (default, hover, disabled). The design is modern and clean, with a focus on usability."
    },
    {
        id: 'item-11',
        title: 'The Art of Negotiation',
        author: 'Musa Adeboye',
        price: 8500,
        imageUrl: 'https://picsum.photos/seed/mp11/600/400',
        imageHint: 'business meeting',
        type: 'eBook',
        isSoldOut: false,
        preview: "Chapter 1: The BATNA Principle. Your 'Best Alternative to a Negotiated Agreement' is your greatest source of power. Before entering any negotiation, you must know what you will do if you fail to reach a deal. This chapter walks you through identifying your BATNA, strengthening it, and assessing the other party's BATNA."
    },
    {
        id: 'item-12',
        title: 'Meal Prep Like a Pro',
        author: 'Dayo Olumide',
        price: 6500,
        imageUrl: 'https://picsum.photos/seed/mp12/600/400',
        imageHint: 'healthy food',
        type: 'Guide',
        isSoldOut: false,
        preview: "Step 1: Plan Your Menu. Don't just cook random things. For the next week, decide what you'll have for breakfast, lunch, and dinner. This guide includes a sample one-week meal plan with a corresponding shopping list to get you started. The preview shows the first three days of the plan, including recipes for overnight oats and chicken salad."
    },
    {
        id: 'item-13',
        title: 'Local SEO Checklist',
        author: 'Segun Arinze',
        price: 16000,
        imageUrl: 'https://picsum.photos/seed/mp13/600/400',
        imageHint: 'local map',
        type: 'Template',
        isSoldOut: false,
        preview: "A watermarked checklist is shown. Key items include: 'Claim & Optimize Google Business Profile', 'Build Local Citations (NAP Consistency)', 'Get Local Reviews', and 'Optimize Website for Local Keywords'. This preview shows the first 5 of 20 essential steps for ranking higher in local search results."
    },
    {
        id: 'item-14',
        title: 'JavaScript Algorithms Course',
        author: 'Bolanle Adebayo',
        price: 28000,
        imageUrl: 'https://picsum.photos/seed/mp14/600/400',
        imageHint: 'javascript code',
        type: 'Guide',
        isSoldOut: false,
        preview: "Algorithm 1: Two Sum. Given an array of integers, return indices of the two numbers such that they add up to a specific target. This is a classic interview question. The preview provides the problem statement, a brute-force solution, and an optimized solution using a hash map, with code comments explaining the logic."
    },
    {
        id: 'item-15',
        title: 'Photography Presets for Lightroom',
        author: 'Jide Sanusi',
        price: 14000,
        imageUrl: 'https://picsum.photos/seed/mp15/600/400',
        imageHint: 'photo editing',
        type: 'Tool',
        isSoldOut: false,
        preview: "This pack includes 5 presets for Adobe Lightroom: 'Cinematic Teal', 'Moody Portrait', and 'Vibrant Landscape'. The preview shows three 'before and after' comparison images, all watermarked. One shows a dull cityscape transformed into a vibrant, cinematic scene. Another shows a basic portrait given a moody, dramatic look."
    },
    {
        id: 'item-16',
        title: 'How to Launch a Podcast',
        author: 'Habiba Ibrahim',
        price: 9000,
        imageUrl: 'https://picsum.photos/seed/mp16/600/400',
        imageHint: 'microphone podcast',
        type: 'eBook',
        isSoldOut: false,
        preview: "Chapter 1: Finding Your Niche. What are you passionate about? What could you talk about for hours? The most successful podcasts are born from genuine passion. This chapter includes a worksheet with 10 questions to help you brainstorm and identify a unique niche for your podcast that you can be excited about."
    },
];

export const swapRequests: SwapRequest[] = [
  {
    id: 'swap-1',
    user: users.find(u => u.id === 'user-2')!,
    offeredSkill: 'Web Development',
    requestedSkill: 'Graphic Design',
    status: 'accepted',
    date: '2024-05-25T10:00:00Z',
    message: 'Hey Adanna, I saw you needed a hand with some web dev stuff. I\'d love to trade for some branding help for my new project!',
  },
  {
    id: 'swap-2',
    user: users.find(u => u.id === 'user-4')!,
    offeredSkill: 'Fitness Coaching',
    requestedSkill: 'Social Media Marketing',
    status: 'pending',
    date: '2024-05-28T14:00:00Z',
    message: 'Hi, I can get you set up with a full fitness plan. I need some help growing my Instagram presence. Let me know if you\'re interested.',
  },
  {
    id: 'swap-3',
    user: users.find(u => u.id === 'user-3')!,
    offeredSkill: 'Creative Writing',
    requestedSkill: 'Personal Finance',
    status: 'pending',
    date: '2024-06-01T11:00:00Z',
    message: 'I can help you write compelling copy for your website. I need some advice on how to manage my freelance income. Can you help?',
  },
  {
    id: 'swap-4',
    user: users.find(u => u.id === 'user-5')!,
    offeredSkill: 'Carpentry',
    requestedSkill: 'Guitar',
    status: 'completed',
    date: '2024-04-15T18:00:00Z',
    message: 'Built a custom shelf for Bolanle, and he taught me the basics of guitar. Great experience!',
  },
    {
    id: 'swap-5',
    user: users.find(u => u.id === 'user-6')!,
    offeredSkill: 'Public Speaking',
    requestedSkill: 'React',
    status: 'declined',
    date: '2024-05-20T12:00:00Z',
    message: 'I was hoping to learn React, but it looks like our schedules just don\'t line up. Maybe another time!',
  }
]
