import type { User, Conversation } from "@/lib/types";
import placeholderData from "@/lib/placeholder-images.json";

const { placeholderImages } = placeholderData;

const imageMap = new Map(placeholderImages.map(image => [image.id, image]));

const findImage = (id: string) => {
    const image = imageMap.get(id);
    return {
        imageUrl: image?.imageUrl ?? `https://placehold.co/200x200?text=${id}`,
        imageHint: image?.imageHint ?? "placeholder"
    };
};

export const users: User[] = [
  {
    id: "user-1",
    name: "Alice Johnson",
    email: "alice@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Passionate graphic designer with a love for typography and branding. Looking to learn pottery to unwind and create with my hands.",
    location: "New York, NY",
    skillsOffered: [
      { id: "skill-1", name: "Graphic Design" },
      { id: "skill-2", name: "Illustration" },
      { id: "skill-3", name: "Branding" },
    ],
    skillsNeeded: [
      { id: "skill-10", name: "Pottery" },
      { id: "skill-11", name: "Creative Writing" },
    ],
  },
  {
    id: "user-2",
    name: "Bob Williams",
    email: "bob@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Software developer by day, aspiring chef by night. I can build you a website in exchange for some authentic Italian cooking lessons.",
    location: "San Francisco, CA",
    skillsOffered: [
      { id: "skill-4", name: "Web Development" },
      { id: "skill-5", name: "React" },
      { id: "skill-6", name: "Node.js" },
    ],
    skillsNeeded: [
      { id: "skill-12", name: "Cooking" },
      { id: "skill-13", name: "Guitar" },
    ],
  },
  {
    id: "user-3",
    name: "Charlie Brown",
    email: "charlie@example.com",
    avatarUrl: findImage("user-3").imageUrl,
    avatarHint: findImage("user-3").imageHint,
    bio: "I'm a writer and editor looking to get my finances in order. I can help you with your blog or manuscript!",
    location: "London, UK",
    skillsOffered: [
      { id: "skill-11", name: "Creative Writing" },
      { id: "skill-7", name: "Editing" },
      { id: "skill-8", name: "Content Strategy" },
    ],
    skillsNeeded: [
      { id: "skill-14", name: "Personal Finance" },
      { id: "skill-1", name: "Graphic Design" },
    ],
  },
  {
    id: "user-4",
    name: "Diana Prince",
    email: "diana@example.com",
    avatarUrl: findImage("user-4").imageUrl,
    avatarHint: findImage("user-4").imageHint,
    bio: "Fitness instructor and nutritionist. I can create a personalized workout and meal plan for you. Seeking help with social media marketing.",
    location: "Miami, FL",
    skillsOffered: [
      { id: "skill-9", name: "Fitness Coaching" },
      { id: "skill-15", name: "Nutrition Planning" },
    ],
    skillsNeeded: [
      { id: "skill-16", name: "Social Media Marketing" },
      { id: "skill-4", name: "Web Development" },
    ],
  },
  {
    id: "user-5",
    name: "Ethan Hunt",
    email: "ethan@example.com",
    avatarUrl: findImage("user-5").imageUrl,
    avatarHint: findImage("user-5").imageHint,
    bio: "Skilled carpenter and woodworker. Can build custom furniture. I'd love to learn how to play the guitar.",
    location: "Austin, TX",
    skillsOffered: [
        { id: "skill-17", name: "Carpentry" },
        { id: "skill-18", name: "Woodworking" },
    ],
    skillsNeeded: [
        { id: "skill-13", name: "Guitar" },
    ],
  },
   {
    id: "user-6",
    name: "Fiona Glenanne",
    email: "fiona@example.com",
    avatarUrl: findImage("user-6").imageUrl,
    avatarHint: findImage("user-6").imageHint,
    bio: "Expert in public speaking and presentation skills. Looking to learn basic coding to build a personal project.",
    location: "Chicago, IL",
    skillsOffered: [
        { id: "skill-19", name: "Public Speaking" },
        { id: "skill-20", name: "Presentation Design" },
    ],
    skillsNeeded: [
        { id: "skill-5", name: "React" },
        { id: "skill-6", name: "Node.js" },
    ],
  },
  {
    id: "user-7",
    name: "George Costanza",
    email: "george@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Architect looking to trade building design tips for learning about urban gardening.",
    location: "New York, NY",
    skillsOffered: [{ id: "skill-21", name: "Architecture" }],
    skillsNeeded: [{ id: "skill-22", name: "Urban Gardening" }],
  },
  {
    id: "user-8",
    name: "Hannah Montana",
    email: "hannah@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Pop star by night, normal teen by day. Can teach singing in exchange for advanced math tutoring.",
    location: "Malibu, CA",
    skillsOffered: [{ id: "skill-23", name: "Singing" }],
    skillsNeeded: [{ id: "skill-24", name: "Advanced Math" }],
  },
  {
    id: "user-9",
    name: "Isaac Newton",
    email: "isaac@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "I've got a few laws of physics to share. I'm interested in learning about modern-day alchemy, or 'chemistry' as you call it.",
    location: "Woolsthorpe, UK",
    skillsOffered: [{ id: "skill-25", name: "Physics" }],
    skillsNeeded: [{ id: "skill-26", name: "Chemistry" }],
  },
  {
    id: "user-10",
    name: "Jane Smith",
    email: "jane@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "I'm a photographer who wants to learn how to bake sourdough bread. I can take professional portraits for you!",
    location: "Portland, OR",
    skillsOffered: [{ id: "skill-27", name: "Photography" }],
    skillsNeeded: [{ id: "skill-28", name: "Baking" }],
  },
  {
    id: "user-11",
    name: "Kevin McCallister",
    email: "kevin@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Expert in home defense systems. Looking for someone to teach me how to speak French.",
    location: "Chicago, IL",
    skillsOffered: [{ id: "skill-29", name: "Home Security" }],
    skillsNeeded: [{ id: "skill-30", name: "French" }],
  },
  {
    id: "user-12",
    name: "Laura Palmer",
    email: "laura@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Homecoming queen. I can teach you about... secrets. Looking to learn knitting.",
    location: "Twin Peaks, WA",
    skillsOffered: [{ id: "skill-31", name: "Charisma" }],
    skillsNeeded: [{ id: "skill-32", name: "Knitting" }],
  },
  {
    id: "user-13",
    name: "Michael Scott",
    email: "michael@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "World's Best Boss. Can teach management and improv comedy. Need help with my video editing for 'Threat Level Midnight'.",
    location: "Scranton, PA",
    skillsOffered: [{ id: "skill-33", name: "Management" }, { id: "skill-34", name: "Improv" }],
    skillsNeeded: [{ id: "skill-35", name: "Video Editing" }],
  },
  {
    id: "user-14",
    name: "Nancy Drew",
    email: "nancy@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Amateur detective. I can find anything! I'd like to learn car maintenance for my blue roadster.",
    location: "River Heights, USA",
    skillsOffered: [{ id: "skill-36", name: "Sleuthing" }],
    skillsNeeded: [{ id: "skill-37", name: "Car Maintenance" }],
  },
  {
    id: "user-15",
    name: "Oscar Wilde",
    email: "oscar@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "I can teach you the importance of being earnest. In return, I'd like to learn about this 'internet' thing.",
    location: "Dublin, Ireland",
    skillsOffered: [{ id: "skill-38", name: "Witty Repartee" }],
    skillsNeeded: [{ id: "skill-4", name: "Web Development" }],
  },
  {
    id: "user-16",
    name: "Pam Beesly",
    email: "pam@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Artist and former receptionist. I can teach watercolor painting. I'm looking for lessons in public speaking.",
    location: "Scranton, PA",
    skillsOffered: [{ id: "skill-39", name: "Watercolor" }],
    skillsNeeded: [{ id: "skill-19", name: "Public Speaking" }],
  },
  {
    id: "user-17",
    name: "Quentin Tarantino",
    email: "quentin@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "I make films. I can teach you about dialogue and non-linear storytelling. I need someone to teach me how to use a smartphone properly.",
    location: "Hollywood, CA",
    skillsOffered: [{ id: "skill-40", name: "Filmmaking" }],
    skillsNeeded: [{ id: "skill-41", name: "Smartphone Basics" }],
  },
  {
    id: "user-18",
    name: "Rachel Green",
    email: "rachel@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Fashion enthusiast. I can give you a complete style makeover. I want to learn how to cook something other than a trifle with beef.",
    location: "New York, NY",
    skillsOffered: [{ id: "skill-42", name: "Fashion Styling" }],
    skillsNeeded: [{ id: "skill-12", name: "Cooking" }],
  },
  {
    id: "user-19",
    name: "Steve Rogers",
    email: "steve@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "I can do this all day. Can teach strategic leadership and super soldier combat. I need to learn about modern art.",
    location: "Brooklyn, NY",
    skillsOffered: [{ id: "skill-43", name: "Leadership" }],
    skillsNeeded: [{ id: "skill-44", name: "Art History" }],
  },
  {
    id: "user-20",
    name: "Tony Stark",
    email: "tony@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Genius, billionaire, playboy, philanthropist. Can teach robotics and AI. Looking to learn how to relax and do yoga.",
    location: "Malibu, CA",
    skillsOffered: [{ id: "skill-45", name: "Robotics" }],
    skillsNeeded: [{ id: "skill-46", name: "Yoga" }],
  },
  {
    id: "user-21",
    name: "Ursula Le Guin",
    email: "ursula@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "I write stories about other worlds. Can teach world-building and narrative structure. I want to learn about astronomy.",
    location: "Portland, OR",
    skillsOffered: [{ id: "skill-47", name: "World-Building" }],
    skillsNeeded: [{ id: "skill-48", name: "Astronomy" }],
  },
  {
    id: "user-22",
    name: "Victor Frankenstein",
    email: "victor@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "A man of science. Can teach anatomy and reanimation. I'm looking for lessons in ethics and moral philosophy.",
    location: "Geneva, Switzerland",
    skillsOffered: [{ id: "skill-49", name: "Anatomy" }],
    skillsNeeded: [{ id: "skill-50", name: "Ethics" }],
  },
  {
    id: "user-23",
    name: "Walter White",
    email: "walter@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Chemistry teacher. I can teach you a lot about chemistry. I need help with my car wash business.",
    location: "Albuquerque, NM",
    skillsOffered: [{ id: "skill-26", name: "Chemistry" }],
    skillsNeeded: [{ id: "skill-51", name: "Business Management" }],
  },
  {
    id: "user-24",
    name: "Xena",
    email: "xena@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Warrior Princess. Can teach you how to use a chakram and fight for the greater good. I'd like to learn pottery.",
    location: "Amphipolis, Greece",
    skillsOffered: [{ id: "skill-52", name: "Chakram" }],
    skillsNeeded: [{ id: "skill-10", name: "Pottery" }],
  },
  {
    id: "user-25",
    name: "Yoda",
    email: "yoda@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Teach you, I can. Learn, you will. How to build a modern web app, I wish to learn.",
    location: "Dagobah",
    skillsOffered: [{ id: "skill-53", name: "The Force" }],
    skillsNeeded: [{ id: "skill-5", name: "React" }],
  },
  {
    id: "user-26",
    name: "Zelda",
    email: "zelda@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Princess of Hyrule. I can teach royal etiquette and Ocarina songs. I need help fixing my Sheikah Slate.",
    location: "Hyrule",
    skillsOffered: [{ id: "skill-54", name: "Ocarina" }],
    skillsNeeded: [{ id: "skill-55", name: "Electronics Repair" }],
  }
];

export const conversations: Conversation[] = [
  {
    id: "conv-1",
    participant: users[1],
    messages: [
      { id: "msg-1", senderId: "user-2", text: "Hey! I saw you're looking for pottery lessons. I'm a beginner but I have a wheel. Maybe we can practice together?", timestamp: "2024-05-20T10:00:00Z" },
      { id: "msg-2", senderId: "user-1", text: "That sounds great, Bob! I'd love that. I can help you with some logo ideas for your new cooking blog in return.", timestamp: "2024-05-20T10:05:00Z" },
    ],
    get lastMessage() { return this.messages[this.messages.length - 1] },
  },
    {
    id: "conv-2",
    participant: users[2],
    messages: [
      { id: "msg-3", senderId: "user-3", text: "Hi Alice, I need some help with a cover design for my manuscript. Your work is amazing!", timestamp: "2024-05-19T14:30:00Z" },
      { id: "msg-4", senderId: "user-1", text: "Hi Charlie! Thanks so much. I'd be happy to take a look. I'm actually looking for someone to help me brainstorm some story ideas. Maybe we can help each other out?", timestamp: "2024-05-19T14:35:00Z" },
       { id: "msg-5", senderId: "user-3", text: "That's perfect! I'd love to. Let's chat more this week.", timestamp: "2024-05-19T14:40:00Z" },
    ],
    get lastMessage() { return this.messages[this.messages.length - 1] },
  },
];

    