import type { User, Conversation } from "@/lib/types";
import placeholderData from "@/lib/placeholder-images.json";
import { ALL_SKILLS } from "@/lib/skills";

const { placeholderImages } = placeholderData;

const imageMap = new Map(placeholderImages.map(image => [image.id, image]));

const findImage = (id: string) => {
    const image = imageMap.get(id);
    return {
        imageUrl: image?.imageUrl ?? `https://placehold.co/200x200?text=${id}`,
        imageHint: image?.imageHint ?? "placeholder"
    };
};

export const users: User[] = [
  {
    id: "user-1",
    name: "Alice Johnson",
    email: "alice@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Passionate graphic designer with a love for typography and branding. Looking to learn pottery to unwind and create with my hands.",
    location: "New York, NY",
    skillsOffered: ["Graphic Design", "Illustration", "Branding"],
    skillsNeeded: ["Pottery", "Creative Writing"],
  },
  {
    id: "user-2",
    name: "Bob Williams",
    email: "bob@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Software developer by day, aspiring chef by night. I can build you a website in exchange for some authentic Italian cooking lessons.",
    location: "San Francisco, CA",
    skillsOffered: ["Web Development", "React", "Node.js"],
    skillsNeeded: ["Cooking", "Guitar"],
  },
  {
    id: "user-3",
    name: "Charlie Brown",
    email: "charlie@example.com",
    avatarUrl: findImage("user-3").imageUrl,
    avatarHint: findImage("user-3").imageHint,
    bio: "I'm a writer and editor looking to get my finances in order. I can help you with your blog or manuscript!",
    location: "London, UK",
    skillsOffered: ["Creative Writing", "Editing", "Content Strategy"],
    skillsNeeded: ["Personal Finance", "Graphic Design"],
  },
  {
    id: "user-4",
    name: "Diana Prince",
    email: "diana@example.com",
    avatarUrl: findImage("user-4").imageUrl,
    avatarHint: findImage("user-4").imageHint,
    bio: "Fitness instructor and nutritionist. I can create a personalized workout and meal plan for you. Seeking help with social media marketing.",
    location: "Miami, FL",
    skillsOffered: ["Fitness Coaching", "Nutrition Planning"],
    skillsNeeded: ["Social Media Marketing", "Web Development"],
  },
  {
    id: "user-5",
    name: "Ethan Hunt",
    email: "ethan@example.com",
    avatarUrl: findImage("user-5").imageUrl,
    avatarHint: findImage("user-5").imageHint,
    bio: "Skilled carpenter and woodworker. Can build custom furniture. I'd love to learn how to play the guitar.",
    location: "Austin, TX",
    skillsOffered: ["Carpentry", "Woodworking"],
    skillsNeeded: ["Guitar"],
  },
   {
    id: "user-6",
    name: "Fiona Glenanne",
    email: "fiona@example.com",
    avatarUrl: findImage("user-6").imageUrl,
    avatarHint: findImage("user-6").imageHint,
    bio: "Expert in public speaking and presentation skills. Looking to learn basic coding to build a personal project.",
    location: "Chicago, IL",
    skillsOffered: ["Public Speaking", "Presentation Design"],
    skillsNeeded: ["React", "Node.js"],
  },
  {
    id: "user-7",
    name: "George Costanza",
    email: "george@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Architect looking to trade building design tips for learning about urban gardening.",
    location: "New York, NY",
    skillsOffered: ["Architecture"],
    skillsNeeded: ["Urban Gardening"],
  },
  {
    id: "user-8",
    name: "Hannah Montana",
    email: "hannah@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Pop star by night, normal teen by day. Can teach singing in exchange for advanced math tutoring.",
    location: "Malibu, CA",
    skillsOffered: ["Singing"],
    skillsNeeded: ["Calculus"],
  },
  {
    id: "user-9",
    name: "Isaac Newton",
    email: "isaac@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "I've got a few laws of physics to share. I'm interested in learning about modern-day alchemy, or 'chemistry' as you call it.",
    location: "Woolsthorpe, UK",
    skillsOffered: ["Physics"],
    skillsNeeded: ["Chemistry"],
  },
  {
    id: "user-10",
    name: "Jane Smith",
    email: "jane@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "I'm a photographer who wants to learn how to bake sourdough bread. I can take professional portraits for you!",
    location: "Portland, OR",
    skillsOffered: ["Photography"],
    skillsNeeded: ["Baking"],
  },
  {
    id: "user-11",
    name: "Kevin McCallister",
    email: "kevin@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Expert in home defense systems. Looking for someone to teach me how to speak French.",
    location: "Chicago, IL",
    skillsOffered: ["Home Security"],
    skillsNeeded: ["French"],
  },
  {
    id: "user-12",
    name: "Laura Palmer",
    email: "laura@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Homecoming queen. I can teach you about... secrets. Looking to learn knitting.",
    location: "Twin Peaks, WA",
    skillsOffered: ["Event Planning"],
    skillsNeeded: ["Knitting"],
  },
  {
    id: "user-13",
    name: "Michael Scott",
    email: "michael@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "World's Best Boss. Can teach management and improv comedy. Need help with my video editing for 'Threat Level Midnight'.",
    location: "Scranton, PA",
    skillsOffered: ["Sales", "Improv"],
    skillsNeeded: ["Video Editing"],
  },
  {
    id: "user-14",
    name: "Nancy Drew",
    email: "nancy@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Amateur detective. I can find anything! I'd like to learn car maintenance for my blue roadster.",
    location: "River Heights, USA",
    skillsOffered: ["Problem Solving"],
    skillsNeeded: ["Car Maintenance"],
  },
  {
    id: "user-15",
    name: "Oscar Wilde",
    email: "oscar@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "I can teach you the importance of being earnest. In return, I'd like to learn about this 'internet' thing.",
    location: "Dublin, Ireland",
    skillsOffered: ["Playwriting"],
    skillsNeeded: ["Web Development"],
  },
  {
    id: "user-16",
    name: "Pam Beesly",
    email: "pam@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Artist and former receptionist. I can teach watercolor painting. I'm looking for lessons in public speaking.",
    location: "Scranton, PA",
    skillsOffered: ["Watercolor Painting"],
    skillsNeeded: ["Public Speaking"],
  },
  {
    id: "user-17",
    name: "Quentin Tarantino",
    email: "quentin@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "I make films. I can teach you about dialogue and non-linear storytelling. I need someone to teach me how to use a smartphone properly.",
    location: "Hollywood, CA",
    skillsOffered: ["Filmmaking"],
    skillsNeeded: ["Smartphone Basics"],
  },
  {
    id: "user-18",
    name: "Rachel Green",
    email: "rachel@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Fashion enthusiast. I can give you a complete style makeover. I want to learn how to cook something other than a trifle with beef.",
    location: "New York, NY",
    skillsOffered: ["Fashion Styling"],
    skillsNeeded: ["Cooking"],
  },
  {
    id: "user-19",
    name: "Steve Rogers",
    email: "steve@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "I can do this all day. Can teach strategic leadership and super soldier combat. I need to learn about modern art.",
    location: "Brooklyn, NY",
    skillsOffered: ["Leadership"],
    skillsNeeded: ["Art History"],
  },
  {
    id: "user-20",
    name: "Tony Stark",
    email: "tony@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Genius, billionaire, playboy, philanthropist. Can teach robotics and AI. Looking to learn how to relax and do yoga.",
    location: "Malibu, CA",
    skillsOffered: ["Robotics"],
    skillsNeeded: ["Yoga"],
  },
  {
    id: "user-21",
    name: "Ursula Le Guin",
    email: "ursula@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "I write stories about other worlds. Can teach world-building and narrative structure. I want to learn about astronomy.",
    location: "Portland, OR",
    skillsOffered: ["Creative Writing"],
    skillsNeeded: ["Astronomy"],
  },
  {
    id: "user-22",
    name: "Victor Frankenstein",
    email: "victor@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "A man of science. Can teach anatomy and reanimation. I'm looking for lessons in ethics and moral philosophy.",
    location: "Geneva, Switzerland",
    skillsOffered: ["Anatomy"],
    skillsNeeded: ["Ethics"],
  },
  {
    id: "user-23",
    name: "Walter White",
    email: "walter@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Chemistry teacher. I can teach you a lot about chemistry. I need help with my car wash business.",
    location: "Albuquerque, NM",
    skillsOffered: ["Chemistry"],
    skillsNeeded: ["Business Management"],
  },
  {
    id: "user-24",
    name: "Xena",
    email: "xena@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Warrior Princess. Can teach you how to use a chakram and fight for the greater good. I'd like to learn pottery.",
    location: "Amphipolis, Greece",
    skillsOffered: ["Self-Defense"],
    skillsNeeded: ["Pottery"],
  },
  {
    id: "user-25",
    name: "Yoda",
    email: "yoda@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: findImage("user-2").imageHint,
    bio: "Teach you, I can. Learn, you will. How to build a modern web app, I wish to learn.",
    location: "Dagobah",
    skillsOffered: ["Meditation"],
    skillsNeeded: ["React"],
  },
  {
    id: "user-26",
    name: "Zelda",
    email: "zelda@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: findImage("user-1").imageHint,
    bio: "Princess of Hyrule. I can teach royal etiquette and Ocarina songs. I need help fixing my Sheikah Slate.",
    location: "Hyrule",
    skillsOffered: ["Music"],
    skillsNeeded: ["Electronics Repair"],
  },
  {
    id: "user-27",
    name: "Albus Dumbledore",
    email: "albus@hogwarts.edu",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "wise wizard",
    bio: "Headmaster. Can offer lessons in transfiguration and defense against the dark arts. Seeking to understand 'the internet'.",
    location: "Hogwarts, Scotland",
    skillsOffered: ["Transfiguration", "Ancient Runes" ],
    skillsNeeded: ["Web Development"]
  },
  {
    id: "user-28",
    name: "Beatrix Kiddo",
    email: "beatrix@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "female warrior",
    bio: "Can teach sword fighting and the five-point-palm exploding heart technique. I'm interested in learning how to knit.",
    location: "El Paso, TX",
    skillsOffered: ["Swordsmanship"],
    skillsNeeded: ["Knitting"]
  },
  {
    id: "user-29",
    name: "Cosmo Kramer",
    email: "kramer@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "quirky man",
    bio: "I'm full of ideas! I can teach you about physical comedy and making a grand entrance. I need someone to help me with my taxes.",
    location: "New York, NY",
    skillsOffered: ["Improv"],
    skillsNeeded: ["Personal Finance"]
  },
  {
    id: "user-30",
    name: "Dana Scully",
    email: "scully@fbi.gov",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "female detective",
    bio: "Medical doctor and FBI agent. I can teach you about forensic science and skepticism. I'm looking to learn photography.",
    location: "Washington D.C.",
    skillsOffered: ["Forensic Science"],
    skillsNeeded: ["Photography"]
  },
  {
    id: "user-31",
    name: "Elaine Benes",
    email: "elaine@example.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "woman city",
    bio: "I work in publishing. I can edit your manuscript and teach you how to dance... sort of. I want to learn how to do my own plumbing.",
    location: "New York, NY",
    skillsOffered: ["Editing"],
    skillsNeeded: ["Plumbing"]
  },
  {
    id: "user-32",
    name: "Fox Mulder",
    email: "mulder@fbi.gov",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "male detective",
    bio: "I want to believe. Can teach you about unsolved mysteries and the paranormal. Looking for someone to teach me advanced basketball techniques.",
    location: "Washington D.C.",
    skillsOffered: ["Creative Writing"],
    skillsNeeded: ["Basketball"]
  },
  {
    id: "user-33",
    name: "Gordon Ramsay",
    email: "gordon@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "chef angry",
    bio: "I can teach you how to cook like a real chef. Don't be an idiot sandwich. I'd like to learn how to be more patient.",
    location: "London, UK",
    skillsOffered: ["Cooking"],
    skillsNeeded: ["Meditation"]
  },
  {
    id: "user-34",
    name: "Hermione Granger",
    email: "hermione@hogwarts.edu",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "student wizard",
    bio: "I can help you with pretty much any subject. I'm particularly good at Arithmancy. I want to learn how to use a computer.",
    location: "Hogwarts, Scotland",
    skillsOffered: ["Research"],
    skillsNeeded: ["Computer Basics"]
  },
  {
    id: "user-35",
    name: "Indiana Jones",
    email: "indy@example.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "adventurer fedora",
    bio: "Archaeology professor and adventurer. I can teach you about ancient history and how to use a whip. I need to learn how to fly a plane.",
    location: "Connecticut, USA",
    skillsOffered: ["Archaeology"],
    skillsNeeded: ["Piloting"]
  },
  {
    id: "user-36",
    name: "Jack Sparrow",
    email: "captainjack@sea.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "pirate captain",
    bio: "Captain. I can teach you how to sail and find treasure. Savvy? I need someone to fix my compass.",
    location: "The Caribbean",
    skillsOffered: ["Sailing"],
    skillsNeeded: ["Electronics Repair"]
  },
  {
    id: "user-37",
    name: "Katniss Everdeen",
    email: "katniss@district12.panem",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "archer woods",
    bio: "I can teach you archery and survival skills. I'd like to learn how to bake.",
    location: "District 12",
    skillsOffered: ["Archery"],
    skillsNeeded: ["Baking"]
  },
  {
    id: "user-38",
    name: "Liz Lemon",
    email: "liz@nbc.com",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "woman office",
    bio: "Head writer for a sketch comedy show. I can teach you how to write jokes. I need help with my night cheese addiction.",
    location: "New York, NY",
    skillsOffered: ["Comedy Writing"],
    skillsNeeded: ["Nutrition Planning"]
  },
  {
    id: "user-39",
    name: "Marty McFly",
    email: "marty@hillvalley.ca",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "teenager 80s",
    bio: "I can play the guitar pretty well. I need someone to help me fix my DeLorean.",
    location: "Hill Valley, CA",
    skillsOffered: ["Guitar"],
    skillsNeeded: ["Car Maintenance"]
  },
  {
    id: "user-40",
    name: "Optimus Prime",
    email: "optimus@autobots.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "robot leader",
    bio: "Leader of the Autobots. I can teach you about leadership and intergalactic diplomacy. I wish to learn about human art.",
    location: "Cybertron",
    skillsOffered: ["Leadership"],
    skillsNeeded: ["Art History"]
  },
  {
    id: "user-41",
    name: "Peter Parker",
    email: "pete@dailybugle.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "young man",
    bio: "I'm a freelance photographer. I can teach you how to take great pictures. I'm trying to learn more about chemistry.",
    location: "Queens, NY",
    skillsOffered: ["Photography"],
    skillsNeeded: ["Chemistry"]
  },
  {
    id: "user-42",
    name: "Ron Swanson",
    email: "ron@pawnee.in.gov",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "man mustache",
    bio: "I enjoy woodworking and breakfast food. I can teach you how to build a canoe. I have no needs.",
    location: "Pawnee, IN",
    skillsOffered: ["Woodworking"],
    skillsNeeded: ["Philosophy"]
  },
  {
    id: "user-43",
    name: "Sarah Connor",
    email: "sarah@resistance.net",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "woman tough",
    bio: "I can teach you how to survive judgment day. I need to learn how to weld.",
    location: "Los Angeles, CA",
    skillsOffered: ["Survival Skills"],
    skillsNeeded: ["Welding"]
  },
  {
    id: "user-44",
    name: "Sherlock Holmes",
    email: "sherlock@221b.baker.st",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "detective classic",
    bio: "Consulting detective. I can teach you the science of deduction. I'm looking for someone to teach me the violin.",
    location: "London, UK",
    skillsOffered: ["Problem Solving"],
    skillsNeeded: ["Violin"]
  },
  {
    id: "user-45",
    name: "Willy Wonka",
    email: "wonka@factory.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "eccentric man",
    bio: "Chocolatier. I can teach you how to make candy. I need help with my factory's accounting.",
    location: "Unknown",
    skillsOffered: ["Baking"],
    skillsNeeded: ["Personal Finance"]
  },
  {
    id: "user-46",
    name: "Anakin Skywalker",
    email: "ani@jedicouncil.org",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "young jedi",
    bio: "Jedi Knight. Expert pilot and lightsaber duelist. I can teach you pod-racing. Looking to learn sand-castle building.",
    location: "Coruscant",
    skillsOffered: ["Piloting", "Swordsmanship"],
    skillsNeeded: ["Sculpting"]
  },
  {
    id: "user-47",
    name: "Bilbo Baggins",
    email: "bilbo@bagend.shire",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "hobbit home",
    bio: "I've been on an adventure. I can teach you map-making and riddles. Seeking lessons in dragon-slaying, just in case.",
    location: "The Shire",
    skillsOffered: ["Storytelling"],
    skillsNeeded: ["Swordsmanship"]
  },
  {
    id: "user-48",
    name: "Carmen Sandiego",
    email: "carmen@vile.org",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "woman red",
    bio: "International art thief. I can teach you geography and history. Looking for someone to teach me how to code.",
    location: "Everywhere",
    skillsOffered: ["Geography"],
    skillsNeeded: ["Web Development"]
  },
  {
    id: "user-49",
    name: "Doctor Who",
    email: "the.doctor@tardis.time",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "time traveler",
    bio: "Time Lord. I can teach you about all of time and space. I need help fixing my chameleon circuit.",
    location: "Everywhen",
    skillsOffered: ["History"],
    skillsNeeded: ["Electronics Repair"]
  },
  {
    id: "user-50",
    name: "Forrest Gump",
    email: "forrest@bubbagump.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "man simple",
    bio: "I'm not a smart man, but I know what love is. I can teach you how to run, play ping-pong, and shrimp. I want to learn about computers.",
    location: "Greenbow, AL",
    skillsOffered: ["Running"],
    skillsNeeded: ["Web Development"]
  },
  {
    id: "user-51",
    name: "Gollum",
    email: "myprecious@middle-earth.net",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "creature dark",
    bio: "We knows riddles, yes we do. We can teach you how to catch fish with our hands. We needs our precious.",
    location: "Misty Mountains",
    skillsOffered: ["Riddles"],
    skillsNeeded: ["Jewelry Making"]
  },
  {
    id: "user-52",
    name: "James Bond",
    email: "007@mi6.gov.uk",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "spy tuxedo",
    bio: "Shaken, not stirred. I can teach you espionage and card games. I'm looking for someone to teach me how to make a proper martini at home.",
    location: "London, UK",
    skillsOffered: ["Problem Solving"],
    skillsNeeded: ["Mixology"]
  },
  {
    id: "user-53",
    name: "Legolas",
    email: "legolas@mirkwood.elf",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "elf archer",
    bio: "Elf of the woodland realm. My eyes are keen. I can teach you archery and how to walk on snow. I wish to learn the ways of the Dwarves.",
    location: "Mirkwood",
    skillsOffered: ["Archery"],
    skillsNeeded: ["Stonemasonry"]
  },
  {
    id: "user-54",
    name: "Mary Poppins",
    email: "mary@cherrytreelane.uk",
    avatarUrl: findImage("user-1").imageUrl,
    avatarHint: "nanny vintage",
    bio: "Practically perfect in every way. I can teach you how to have a tidy nursery and how to fly a kite. I'm looking to learn how to skateboard.",
    location: "London, UK",
    skillsOffered: ["Child Care"],
    skillsNeeded: ["Skateboarding"]
  },
  {
    id: "user-55",
    name: "Neo",
    email: "thomas.anderson@metacortex.com",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "man trenchcoat",
    bio: "I know kung fu. I can teach you how to free your mind. I need someone to explain what 'tastee wheat' is.",
    location: "The Matrix",
    skillsOffered: ["Kung Fu"],
    skillsNeeded: ["Cooking"]
  },
  {
    id: "user-56",
    name: "Rocky Balboa",
    email: "rocky@philly.net",
    avatarUrl: findImage("user-2").imageUrl,
    avatarHint: "boxer determined",
    bio: "It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward. I can teach you boxing. I want to learn how to read better.",
    location: "Philadelphia, PA",
    skillsOffered: ["Boxing"],
    skillsNeeded: ["Literacy"]
  }
];


export const conversations: Conversation[] = [
  {
    id: "conv-1",
    participant: users.find(u => u.id === 'user-2')!,
    messages: [
      { id: "msg-1", senderId: "user-2", text: "Hey! I saw you're looking for pottery lessons. I'm a beginner but I have a wheel. Maybe we can practice together?", timestamp: "2024-05-20T10:00:00Z" },
      { id: "msg-2", senderId: "user-1", text: "That sounds great, Bob! I'd love that. I can help you with some logo ideas for your new cooking blog in return.", timestamp: "2024-05-20T10:05:00Z" },
    ],
    get lastMessage() { return this.messages[this.messages.length - 1] },
  },
    {
    id: "conv-2",
    participant: users.find(u => u.id === 'user-3')!,
    messages: [
      { id: "msg-3", senderId: "user-3", text: "Hi Alice, I need some help with a cover design for my manuscript. Your work is amazing!", timestamp: "2024-05-19T14:30:00Z" },
      { id: "msg-4", senderId: "user-1", text: "Hi Charlie! Thanks so much. I'd be happy to take a look. I'm actually looking for someone to help me brainstorm some story ideas. Maybe we can help each other out?", timestamp: "2024-05-19T14:35:00Z" },
       { id: "msg-5", senderId: "user-3", text: "That's perfect! I'd love to. Let's chat more this week.", timestamp: "2024-05-19T14:40:00Z" },
    ],
    get lastMessage() { return this.messages[this.messages.length - 1] },
  },
];
