export const ALL_SKILLS = [
  "Accounting",
  "Acting",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Agile Methodology",
  "AI Development",
  "Analysis",
  "Ancient Runes",
  "Anatomy",
  "Animation",
  "Archaeology",
  "Archery",
  "Architecture",
  "Art History",
  "Astronomy",
  "Baking",
  "Basketball",
  "Blockchain",
  "Blogging",
  "Boxing",
  "Branding",
  "Business Development",
  "Business Management",
  "Calculus",
  "Calligraphy",
  "Car Maintenance",
  "Carpentry",
  "Ceramics",
  "Chemistry",
  "Child Care",
  "Comedy Writing",
  "Computer Basics",
  "Content Marketing",
  "Content Strategy",
  "Cooking",
  "Copywriting",
  "Creative Writing",
  "Cryptography",
  "Data Analysis",
  "Data Science",
  "Data Visualization",
  "Deep Learning",
  "Digital Marketing",
  "Drawing",
  "Editing",
  "Electronics Repair",
  "Email Marketing",
  "Emotional Intelligence",
  "Entrepreneurship",
  "Ethics",
  "Event Planning",
  "Fashion Design",
  "Fashion Styling",
  "Filmmaking",
  "Financial Modeling",
  "Fitness Coaching",
  "Foreign Languages",
  "Forensic Science",
  "French",
  "Game Development",
  "Geography",

  "Glassblowing",
  "Google Ads",
  "Google Analytics",
  "Graphic Design",
  "Guitar",
  "History",
  "Home Security",
  "HTML & CSS",
  "Illustration",
  "Improv",
  "Interior Design",
  "Investing",
  "JavaScript",
  "Jewelry Making",
  "Journalism",
  "Knitting",
  "Kung Fu",
  "Leadership",
  "Leatherworking",
  "Literacy",
  "Logic",
  "Machine Learning",
  "Market Research",
  "Marketing Strategy",
  "Meditation",
  "Mixology",
  "Mobile App Development",
  "Music",
  "Music Production",
  "Negotiation",
  "Node.js",
  "Nutrition Planning",
  "Painting",
  "Personal Finance",
  "Philosophy",
  "Photography",
  "Physics",
  "Piloting",
  "Playwriting",
  "Plumbing",
  "Podcasting",
  "Poetry",
  "Pottery",
  "Presentation Design",
  "Problem Solving",
  "Product Management",
  "Project Management",
  "Psychology",
  "Public Relations",
  "Public Speaking",
  "Python",
  "React",
  "Research",
  "Riddles",
  "Robotics",
  "Running",
  "Sailing",
  "Sales",
  "Sculpting",
  "Self-Defense",
  "SEO (Search Engine Optimization)",
  "Singing",
  "Skateboarding",
  "Smartphone Basics",
  "Social Media Marketing",
  "Songwriting",
  "Spanish",
  "Stonemasonry",
  "Storytelling",
  "Survival Skills",
  "Swordsmanship",
  "Taxes",
  "Teaching",
  "Transfiguration",
  "TypeScript",
  "UI/UX Design",
  "Urban Gardening",
  "Video Editing",
  "Violin",
  "Watercolor Painting",
  "Web Development",
  "Welding",
  "Woodworking",
  "Yoga",
];
